# Generated by Django 4.2.11 on 2024-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_remove_umsuser_instagram_remove_umsuser_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='umsuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
