# Generated by Django 4.2.11 on 2024-10-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_umsuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umsuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='umsuser',
            name='semester',
        ),
    ]
