# Generated by Django 4.2.11 on 2024-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_remove_umsuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='umsuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
