# Generated by Django 4.2.11 on 2025-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_umsuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umsuser',
            name='angkatan',
            field=models.PositiveIntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2025),
        ),
    ]
