# Generated by Django 4.2.11 on 2024-10-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praktikummatkul',
            old_name='id_matkul',
            new_name='matkul',
        ),
        migrations.RenameField(
            model_name='praktikummatkul',
            old_name='id_praktikum',
            new_name='praktikum',
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='praktikum',
            field=models.ForeignKey(choices=[(0, 'Pemrograman Komputer'), (1, 'Statisika'), (2, 'Perancangan Teknik Industri')], on_delete=django.db.models.deletion.CASCADE, to='app_main.praktikum'),
        ),
    ]
