# Generated by Django 4.2.11 on 2024-10-08 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0002_rename_id_matkul_praktikummatkul_matkul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='praktikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.praktikum'),
        ),
        migrations.CreateModel(
            name='Asisten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisi', models.CharField(max_length=100)),
                ('periode', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=9)),
                ('praktikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.praktikum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
