# Generated by Django 4.2.11 on 2024-10-08 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_pendaftaran_praktikum_asisten'),
    ]

    operations = [
        migrations.AddField(
            model_name='asisten',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='asisten',
            name='divisi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asisten',
            name='periode',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2024', max_length=4),
        ),
    ]
