# Generated by Django 4.2.11 on 2024-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_asisten_created_at_alter_asisten_divisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='nilai',
            field=models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2),
        ),
    ]
