# Generated by Django 4.2.11 on 2024-10-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_pendaftaran_nilai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='asisten',
            name='praktikum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.praktikum'),
        ),
        migrations.AddField(
            model_name='asisten',
            name='asistensi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.asistensi'),
        ),
    ]
