# Generated by Django 4.2.11 on 2024-10-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_asistensi_alter_asisten_praktikum_asisten_asistensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistensi',
            name='asistensi_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistensi',
            name='praktikum',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_main.praktikum'),
            preserve_default=False,
        ),
    ]
