# Generated by Django 4.2.11 on 2024-10-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_asistensi_asistensi_name_asistensi_praktikum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asisten',
            name='asistensi',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='praktikum',
            name='min_semester',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.DeleteModel(
            name='Asistensi',
        ),
    ]
