# Generated by Django 4.2.11 on 2024-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_remove_asisten_asistensi_pendaftaran_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persyaratan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/persyaratan/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
