# Generated by Django 4.2.11 on 2024-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_rename_min_semester_praktikum_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='status',
            field=models.IntegerField(choices=[(1, 'Seleksi Pemberkasan'), (2, 'Lolos Seleksi Pemberkasan'), (3, 'Tes Microteaching'), (4, 'Lolos Microteaching'), (5, 'Tes Pemahaman'), (6, 'Lolos Pemahaman'), (7, 'Wawancara Asisten'), (8, 'Lolos Wawancara Asisten'), (9, 'Wawancara Dosen'), (10, 'Lolos Wawancara Dosen'), (11, 'Diterima'), (-1, 'Ditolak')], default=1),
        ),
    ]
