# Generated by Django 4.2.11 on 2024-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_alter_pendaftaran_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
