# Generated by Django 4.2.11 on 2024-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_pendaftaran_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
