# Generated by Django 4.2.11 on 2024-10-31 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_alter_pendaftaran_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='persyaratan',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='mulai_daftar',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='pengumuman',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 23, 8, 15, 23433)),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='periode',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='praktikum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_main.praktikum'),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='selesai_daftar',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 23, 8, 15, 23433)),
        ),
    ]
