# Generated by Django 4.2.11 on 2024-10-31 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_persyaratan_edited_at_persyaratan_mulai_daftar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='persyaratan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.persyaratan'),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='pengumuman',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 23, 44, 5, 803581)),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='selesai_daftar',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 23, 44, 5, 803581)),
        ),
    ]
