# Generated by Django 4.2.11 on 2024-10-31 18:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_pendaftaran_persyaratan_alter_persyaratan_pengumuman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persyaratan',
            name='ipk',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AddField(
            model_name='persyaratan',
            name='nilai',
            field=models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('CD', 'CD'), ('D', 'D'), ('DE', 'DE'), ('E', 'E')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='asisten',
            name='periode',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='ipk',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nilai',
            field=models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('CD', 'CD'), ('D', 'D'), ('DE', 'DE'), ('E', 'E')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='mulai_daftar',
            field=models.DateField(default=datetime.date(2024, 11, 1)),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='pengumuman',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='periode',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='selesai_daftar',
            field=models.DateField(default=datetime.date(2024, 11, 22)),
        ),
    ]
