# Generated by Django 4.2.11 on 2024-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_persyaratan_ipk_persyaratan_nilai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='praktikum',
        ),
    ]
