# Generated by Django 4.2.11 on 2024-11-01 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0017_remove_pendaftaran_praktikum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendaftaran",
            old_name="file",
            new_name="berkas",
        ),
        migrations.RenameField(
            model_name="pendaftaran",
            old_name="status",
            new_name="selection_status",
        ),
        migrations.RenameField(
            model_name="persyaratan",
            old_name="file",
            new_name="lampiran",
        ),
        migrations.AlterField(
            model_name="persyaratan",
            name="mulai_daftar",
            field=models.DateField(default=datetime.date(2024, 11, 2)),
        ),
        migrations.AlterField(
            model_name="persyaratan",
            name="pengumuman",
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name="persyaratan",
            name="selesai_daftar",
            field=models.DateField(default=datetime.date(2024, 11, 23)),
        ),
    ]
