# Generated by Django 4.2.11 on 2025-02-21 14:58

import datetime
from django.db import migrations, models
import web_laboratorium.apps.app_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0020_remove_pendaftaran_catatan_wa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asisten',
            name='periode',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default='2025', max_length=4),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nilai_tm',
            field=models.JSONField(blank=True, null=True, validators=[web_laboratorium.apps.app_main.models.validate_tes_microteaching]),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='mulai_daftar',
            field=models.DateField(default=datetime.date(2025, 2, 21)),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='pengumuman',
            field=models.DateField(default=datetime.date(2025, 4, 22)),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='periode',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default='2025', max_length=4),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='selesai_daftar',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
        ),
    ]
