# Generated by Django 4.2.11 on 2024-05-07 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/uploads/pendaftaran/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('praktikum', models.CharField(choices=[('1', 'Praktikum 1'), ('2', 'Praktikum 2'), ('3', 'Praktikum 3')], max_length=100)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diproses', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
