# Generated by Django 4.2.11 on 2024-05-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='user',
            new_name='user',
        ),
    ]
