# Generated by Django 4.2.11 on 2024-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_rename_id_user_pendaftaran_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='file',
            field=models.FileField(upload_to='uploads/pendaftaran/'),
        ),
    ]
