# Generated by Django 4.2.11 on 2024-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_pendaftaran_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='praktikum',
            field=models.CharField(choices=[('Praktikum Pemrograman Komputer', 'Praktikum Pemrograman Komputer'), ('Praktikum Statisika', 'Praktikum Statisika'), ('Praktikum Perancangan Teknik Industri', 'Praktikum Perancangan Teknik Industri')], max_length=100),
        ),
    ]
