# Generated by Django 4.2.11 on 2024-05-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_pendaftaran_praktikum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='praktikum',
            field=models.CharField(choices=[('prokom', 'Pemrograman Komputer'), ('Statis', 'Statisika'), ('pti', 'Perancangan Teknik Industri')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='status',
            field=models.CharField(choices=[('pemberkasan', 'Seleksi Pemberkasan'), ('tes', 'Lolos Tes'), ('w_asisten', 'Lolos Wawancara Asisten'), ('w_dosen', 'Lolos Wawancara Dosen'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diproses', max_length=100),
        ),
    ]
