# Generated by Django 4.2.11 on 2024-10-08 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_pendaftaran_praktikum_alter_pendaftaran_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Praktikum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicum_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='ipk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nilai',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PraktikumMatkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.matkul')),
                ('id_praktikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.praktikum')),
            ],
        ),
    ]
